apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "pyhton-docker.fullname" . }}
  labels:
    app: {{ include "pyhton-docker.name" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "pyhton-docker.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "pyhton-docker.name" . }}

    spec:
      containers:
        - name: pyhton-docker

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}