apiVersion: v1
kind: Service

metadata:
  name: {{ include "pyhton-docker.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "pyhton-docker.name" . }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP