replicaCount: 2

image:
  repository: 201937185028.dkr.ecr.ap-south-1.amazonaws.com/pyhton-docker
  tag: "YOUR_SHA"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi