name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'helm/pyhton-docker/values.yaml'

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::201937185028:role/GitHub-ECR-Role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image variables
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=pyhton-docker" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/pyhton-docker:${IMAGE_TAG} \
            .

      - name: Push Docker image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/pyhton-docker:${IMAGE_TAG}

      - name: Update Helm image tag
        run: |
          sed -i 's/^  tag:.*/  tag: "'"${IMAGE_TAG}"'"/' \
            helm/pyhton-docker/values.yaml

          echo "Updated Helm image tag:"
          grep -A2 '^image:' helm/pyhton-docker/values.yaml

      - name: Commit and push Helm update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add helm/pyhton-docker/values.yaml

          git commit -m "Update image to ${IMAGE_TAG}"

          git push origin master